### ISSUE TITLE
PRAISE - using 1e18 as exchangeRate in BaseERC4626Proxy.sol will cause precision errors when converting to shares and converting to assets for some assets

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-notional-judging#112]
PRAISE

high

# using 1e18 as exchangeRate in BaseERC4626Proxy.sol will cause precision errors when converting to shares and converting to assets for some assets

## Summary
Assuming 1e18, will cause precision loss

## Vulnerability Detail
1e18 is used as exchangeRate in BaseERC4626Proxy.sol, but some tokens decimals aren't 18 decimals.. like  WBTC which has 8 decimals and USDC on ARBITRUM which has 6 decimals. 

Assuming 1e18 will cause precision loss when `convertToShares()` and `convertToAssets()` functions are used for WBTC and USDC on ARBITRUM. (there will be a deployment on Arbitrum soon)

## Impact
precision loss when `convertToShares()` and `convertToAssets()` functions are used for WBTC and USDC on ARBITRUM.

## Code Snippet
https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/external/proxies/BaseERC4626Proxy.sol#L45

https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/external/proxies/BaseERC4626Proxy.sol#L158-L160

https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/external/proxies/BaseERC4626Proxy.sol#L163-L165
## Tool used

Manual Review

## Recommendation
re-work the exchangeRate to work with token WBTC's 8 decimals and USDC 6 decimals(i.e when its ARBITRUM).

**Comment by Love4codes** [comment]
Escalate for 10 USDC 

This should be an issue because assuming 1e18 (18 decimals) could lead to precision loss

Here's a more detailed explanation of why i think this is an issue.

1. the EXCHANGE_RATE_PRECISION is set to 1e18 here -- https://github.com/sherlock-audit/2023-03-notional/blob/d574b5cce884aa3686ae159c1f2bcdee9f98b1b3/contracts-v2/contracts/external/proxies/BaseERC4626Proxy.sol#L45

2. some tokens supported by notional like WBTC has 8 decimals and USDC (while on  Arbitrum ) has 6 decimals 
3. these functions (convertToShares() and convertToAssets()) use 18 decimals(1e18 i.e  EXCHANGE_RATE_PRECISION ) to calculate the conversion of these tokens which i believe will cause precision loss

**Comment by 0xleastwood** [comment]
> Escalate for 10 USDC
> 
> This should be an issue because assuming 1e18 (18 decimals) could lead to precision loss
> 
> Here's a more detailed explanation of why i think this is an issue.
> 
> 1. the EXCHANGE_RATE_PRECISION is set to 1e18 here -- https://github.com/sherlock-audit/2023-03-notional/blob/d574b5cce884aa3686ae159c1f2bcdee9f98b1b3/contracts-v2/contracts/external/proxies/BaseERC4626Proxy.sol#L45
> 2. some tokens supported by notional like WBTC has 8 decimals and USDC (while on  Arbitrum ) has 6 decimals
> 3. these functions (convertToShares() and convertToAssets()) use 18 decimals(1e18 i.e  EXCHANGE_RATE_PRECISION ) to calculate the conversion of these tokens which i believe will cause precision loss

You can't avoid some precision loss without incorporating some form of rounding. `EXCHANGE_RATE_PRECISION` is intended to limit this loss to what is likely only 1 wei. The `ERC4626` standard implements rounding in opposite directions to favour the vault. However, this seems to already be done in these functions naturally. When converting minted assets to shares, the result is rounded down. When redeeming these shares, the result is also already rounded down.

**Comment by Love4codes** [comment]
I believe the lead watson doesn't truly understand the issue as stated by the watson.

The issue here is that assuming 1e18 for some tokens supported by notional like WBTC that has 8 decimals and USDC (while on Arbitrum ) that has 6 decimals will lead to precision loss. 

This isn't about rounding up or rounding down..
Assuming 18 decimals for a 8 decimal token and a 6 decimal token will cause precision loss which will affect the number of this tokens gotten from the conversion when attempting a conversion via the functions I mentioned above.

**Comment by Love4codes** [comment]
PreviewDeposit() calls convertToShares
PreviewMint() calls convertToAssets
PreviewRedeem() calls convertToAssets
PreviewWithdraw() calls convertToShares

Now values gotten from this preview functions are used in deposit(), mint(), redeem() and withdraw() functions respectively.

Since 18 decimals is used in the calculation for a 8 decimal and 6 decimal token I believe there will be precision loss and the affected values will be used in these functions and this is very critical.

**Comment by 0xleastwood** [comment]
That's the whole point of `EXCHANGE_RATE_PRECISION`, it's there to limit precision loss. `exchangeRate()` has 18 decimals of precision which is why `EXCHANGE_RATE_PRECISION` is used to scale the results of `convertToShares()` up and `convertToAssets()` down.

**Comment by Love4codes** [comment]
> That's the whole point of `EXCHANGE_RATE_PRECISION`, it's there to limit precision loss. `exchangeRate()` has 18 decimals of precision which is why `EXCHANGE_RATE_PRECISION` is used to scale the results of `convertToShares()` up and `convertToAssets()` down.

but its still 1e18 or am i wrong?

**Comment by Love4codes** [comment]
but `EXCHANGE_RATE_PRECISION` is also 18 decimals

**Comment by Love4codes** [comment]
![Screenshot 2023-06-08 at 21 53 43](https://github.com/sherlock-audit/2023-03-notional-judging/assets/103859872/6b6830b7-e1b6-4d76-b69c-dcb508b0164e)

**Comment by Love4codes** [comment]
> 

I'm still asking around in an attempt to fully comprehend this issue.

I was opportiuned to ask Patrick in the secureum server and he said Rounding down is a source of Precision loss.

--

**Comment by Trumpero** [comment]
This issue has no impact since the protocol doesn't implement minting and redeeming for the contracts that inherit the `BaseERC4626Proxy.sol` contract. Therefore, both `convertToShares` and `convertToAssets` functions of `BaseERC4626Proxy.sol` are not being utilized at the current.
https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/external/proxies/nTokenERC20Proxy.sol#L65-L71
https://github.com/sherlock-audit/2023-03-notional/blob/d574b5cce884aa3686ae159c1f2bcdee9f98b1b3/contracts-v2/contracts/external/proxies/PrimeDebtProxy.sol#L75-L81
https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/external/proxies/PrimeCashProxy.sol#L74-L80
Additionally, I believe the precision loss in those functions is only 1 wei. So it should be a non-issue.

**Comment by hrishibhat** [comment]
Result:
Low
Unique
Not a valid high/medium based on the above comments
