### ISSUE TITLE
PRAISE - PauseRouter.sol won't be able to re-route calls to some functions in VaultAccountHealth.sol

### ISSUE THREAD

**Issue by sherlock-admin** [sherlock-audit/2023-03-notional-judging#123]
PRAISE

medium

# PauseRouter.sol won't be able to re-route calls to some functions in VaultAccountHealth.sol

## Summary
the require statements in some functions in VaultAccountHealth.sol, will make re-routing calls in the PauseRouter.sol to it via the fallback() function fail.

## Vulnerability Detail
functions like calculateDepositAmountInDeleverage() function in VaultAccountHealth.sol has this require statement implemented for access control
```solidity
        require(msg.sender == address(this)); // dev: unauthorized
```

now attempting to make a call to it via PauseRouter.sol's `fallback()` function here will fail
```solidity
 fallback() external payable {
        _delegate(getRouterImplementation(msg.sig));
    }
```

## Impact
 re-routing calls to thisfunction via the fallback functions will fail as the require statement will fail.

## Code Snippet
https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/external/actions/VaultAccountHealth.sol#L235

https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/external/PauseRouter.sol#L201-L203

https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/external/PauseRouter.sol#L148
## Tool used

Manual Review

## Recommendation
To interact with this function from the PauseRouter.sol contract, you would need to use a different approach. One possible solution is to have a separate function in the VaultAccountHealth.sol that allows the PauseRouter.sol contract to calculate deposit amount in deleverage. This separate function could include additional access control checks to ensure that only authorized contracts, such as the PauseRouter.sol contract, can call it.

**Comment by Love4codes** [comment]
Escalate for 10 USDC

I strongly believe this is valid because the functions i mentioned above implemented a strange access control mechanism.

```solidity
require(msg.sender == address(this));
```
it expects internal calls, therefore attempting to delegateCall them from the PauseRouter.sol will fail

Also moreover the pauseRouter.sol contract is in scope

**Comment by 0xleastwood** [comment]
> Escalate for 10 USDC
> 
> I strongly believe this is an issue because the functions i mentioned above implemented a strange access control mechanism.
> 
> ```solidity
> require(msg.sender == address(this));
> ```
> 
> it expects internal calls which you'll see here -- https://github.com/sherlock-audit/2023-03-notional/blob/main/contracts-v2/contracts/external/actions/VaultAccountHealth.sol#L235, therefore attempting to delegateCall them from the PauseRouter.sol will fail
> 
> Also moreover the pauseRouter.sol contract is in scope

I mean it's true that this function will fail to execute when called via `Router.sol` or `PauseRouter.sol`, however, there isn't any actual issue caused by this. This method is intended to only be used when liquidators deleverage an account so it isn't entirely important as a standalone view function. Additionally, calls to this function can be simulated by spoofing `msg.sender` on a local node, so it is still possible for this function to be queried off-chain if necessary.

**Comment by 0xleastwood** [comment]
Actually, I should correct myself here. When `VaultLiquidationAction.deleverageAccount()` performs the `IVaultAccountHealth(address(this)).calculateDepositAmountInDeleverage()` call, `msg.sender` in this context will be `address(this)`, so this check will be successful. There is no need to allow this to be callable under other situations, but as I said above, this can be done by simulating a transaction to the router contract, setting `msg.sender` to `address(this)`.

**Comment by Love4codes** [comment]
"Actually, I should correct myself here. When VaultLiquidationAction.deleverageAccount() performs the IVaultAccountHealth(address(this)).calculateDepositAmountInDeleverage() call, msg.sender in this context will be address(this), so this check will be successful"

**calling the VaultAccountHealth.calculateDepositAmountInDeleverage() function via pauseRouter.sol here is the issue and not calls from --VaultLiquidationAction.deleverageAccount()** 


"I mean it's true that this function will fail to execute when called via Router.sol or PauseRouter.sol, however, there isn't any actual issue caused by this."

**if there's a situation where there's a need to calculate Deposit Amount In Deleverage via the pauseRouter.sol it will fail..**

**And come to think of it there must be a reason why they try to delegateCall it via the pauseRouter.sol, they won't be able to achieve that because the calls will fail**

"This method is intended to only be used when liquidators deleverage an account so it isn't entirely important as a standalone view function"

**VaultAccountHealth.calculateDepositAmountInDeleverage() function is not a view function**

**Comment by Love4codes** [comment]
"I mean it's true that this function will fail to execute when called via Router.sol or PauseRouter.sol, however, there isn't any actual issue caused by this."

**_if there's a situation where there's a need to call and calculate Deposit Amount In Deleverage via the pauseRouter.sol it will fail.._**

**_And come to think of it there must be a reason why they try to delegateCall it via the pauseRouter.sol, they won't be able to achieve that because the calls will fail_**

**Comment by Love4codes** [comment]
"This method is intended to only be used when liquidators deleverage an account so it isn't entirely important as a standalone view function"

**_VaultAccountHealth.calculateDepositAmountInDeleverage() function is not a view function_**

**Comment by 0xleastwood** [comment]
It is not possible for `VaultLiquidationAction.deleverageAccount()` to call `VaultAccountHealth.calculateDepositAmountInDeleverage()` without re-routing via `Router.sol`. Therefore, it's necessary that it calls `IVaultAccountHealth(address(this)).calculateDepositAmountInDeleverage()` because the function is not exposed internally. Notional uses a shared global storage between many of it's contracts but they are functionally separate from each other.

**Comment by Love4codes** [comment]
okay that makes sense

**Comment by Love4codes** [comment]
I also strongly believe my recommended mitigation will help solve this issue

**Comment by 0xleastwood** [comment]
Delegate calls do not alter `msg.sender`.

**Comment by Love4codes** [comment]
![Uploading Screenshot 2023-06-04 at 14.55.45.png…]()

**Comment by Trumpero** [comment]
I believe the warden was misled regarding the behavior of `delegatecall`. It is a known fact, as mentioned in the comment by Leastwood, that `delegatecall` does not alter `msg.sender`. Hence, I believe this issue should be invalid.
P.S: I kindly request you to stop using ChatGPT as evidence or reference, as it may not always provide accurate information. Instead, it would be more appropriate to provide a proof of concept (POC) or reliable references/code snippets to support your claims.

**Comment by hrishibhat** [comment]
Result:
Invalid
Unique
This is a non-issue as the Watson clearly misunderstands the functioning of the above contracts through delegatecall.
